create table if not exists public.movies (
  id bigint generated by default as identity primary key,
  tvdb_id text unique not null,
  title text not null,
  overview text,
  release_date date,
  genres jsonb not null default '[]'::jsonb,
  themes jsonb not null default '[]'::jsonb,
  keywords jsonb not null default '[]'::jsonb,
  cast_members jsonb not null default '[]'::jsonb,
  crew jsonb not null default '[]'::jsonb,
  runtime integer,
  poster_url text,
  backdrop_url text,
  language text,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists movies_title_search_idx on public.movies using gin (to_tsvector('english', title));
create index if not exists movies_updated_at_idx on public.movies (updated_at desc);

create table if not exists public.user_ratings (
  id bigint generated by default as identity primary key,
  user_id uuid,
  movie_id bigint not null references public.movies(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  created_at timestamptz not null default now()
);

create table if not exists public.watch_history (
  id bigint generated by default as identity primary key,
  user_id uuid,
  movie_id bigint not null references public.movies(id) on delete cascade,
  watched_at timestamptz not null default now()
);
